### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by kandros** [twidgeapp/twidge#9]
Hi @VarunPotti, I think adding some screenshots in the readme could help better understanding the project.

**Comment by VarunPotti** [comment]
Hey @kandros, I am working on a landing page right now. The ui is still being built as we speak (and I am not able to get it done quickly as I am having exams next week). I will make sure to get the landing page deployed and have screenshots in the readme once I get it done.

**Comment by VarunPotti** [comment]
However I have posted a video on Twitter(https://twitter.com/PottiVarun/status/1561711195262193664) which I might add in the readme
